apiVersion: spec.keptn.sh/0.2.2
kind: KeptnShipyard
metadata:
    name: ""
spec:
    stages:
        - name: production
          sequences:
            - name: artifact-delivery
              tasks:
                - name: promotion
                  properties: null
                - name: deployment
                  properties:
                    deploymentstrategy: user_managed
        - name: dev
          sequences:
            - name: artifact-delivery
              tasks:
                - name: promotion
                  properties: null
                - name: deployment
                  properties:
                    deploymentstrategy: user_managed
        - name: hardening
          sequences:
            - name: artifact-delivery
              tasks:
                - name: promotion
                  properties: null
                - name: deployment
                  properties:
                    deploymentstrategy: user_managed
