apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "podtato-head"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "dummy"
          tasks:
            - name: "dummy"
    - name: "hardening"
      sequences:
        - name: "dummy"
          tasks:
            - name: "dummy"
    - name: "production"
      sequences:
        - name: "dummy"
          tasks:
            - name: "dummy"

